### ISSUE TITLE
Downloadable/Virtual Products in Grouped Products are sent as physical type

### ISSUE THREAD

**Issue by Sental** [mollie/magento2#590]
**Describe the bug**
Downloadable/Virtual Products in Grouped Products are sent as physical type in the orders api.
This requires the product to be shipped for klarna orders to be successfully processed. Shipping a virtual product in magento is impossible.

This also applies for all virtual products that are not shipped.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5-p1
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 2.18.1

**To Reproduce**
1. add a downloadable product as a child of a grouped product
2. purchase the downloadable product through the group
3. complete the order
4. See the product type in the api call

**Expected behavior**
The product is set to being type digital and the order is shipped and settled correctly.

**Actual behavior**
The product is set as type physical and the order can never be completely shipped or settled correctly.

**Screenshots**

**Additional context**
This stops the successful settlement of these orders that pay with klarna pay later.
See mollie/magento2/Service/Order/Lines/Order.php L176

**Comment by Frank-Magmodules** [comment]
Hi @Sental ,

We are happy to share that we've just released the new [2.20.0](https://github.com/mollie/magento2/releases/tag/v2.20.0) version where we have covered this. Thank you for opening this issue together with the detailed steps to reproduce as well as the PR that you have shared! We've added a "_Thanks for sharing!_" in the release notes as well.

We are closing this issue now but please feel free to reopen the issue if you need any help on this.

**Comment by simonmaass** [comment]
@Sental After applying ur PR I can see that the product in the basket in mollie is now of type "digital"... but it looks like that mollie still wants to have digital products shipped - which is not possible in magento:

Order Basket in Mollie:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/32599710/207366339-8723a7d0-4497-4fc8-8a52-d6459e974b50.png">

Order still not completed after shipping all order items in magento:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/32599710/207366547-ccf326aa-ab82-4f1c-b117-9f74402e0ec9.png">

**Comment by Sental** [comment]
@simonmaass That is correct. This PR & Issue now sends the correct data to Mollie, a digital product is now marked as digital. This was an issue before the changes in the PR. Mollie themselves have been made aware of this behaviour and that it is not compatible with the Magento platform as standard. Currently I've left it with them to discuss and decide a solution.

**Comment by Frank-Magmodules** [comment]
HI @Sental and @simonmaass , we've now developed the feature that the digital-product type is marked as shipped on Mollie's side directly after the invoice is created within Magento. Hopefully, this will cover the scenario that @simonmaass had on the non-shipped order line within Mollie. I've personally sent the change to @simonmaass and this will be available for the public within the next release.
