### ISSUE TITLE
[1.4.0 BETA] - Base table or view not found

### ISSUE THREAD

**Issue by albsa** [mollie/magento2#83]
Hi @Frank-Magmodules,

Just tried it out but I am getting this error when I try to proceed to the checkout with Klarna Pay Later.
ERROR: error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.mollie_order_lines' doesn't exist, query was: DESCRIBE `mollie_order_lines` [] []

After the page load I get redirected back to the cart.

iDEAL was working fine.

Running on M2 v2.2.6
PHP 7.1.18

Runned all CLI commands, but still seeing this issue.
Seems that this table this not get created after running setup:upgrade.

Also got a small notice during activation of the payment method in the admin.
It stated that this payment method was not activated in the account, but it is activated.
It show up on the front-end so that seems fine.

**Comment by albsa** [comment]
Running on module version 1.4.0.x dev

**Comment by albsa** [comment]
@Marvin-Magmodules

**Comment by Marvin-Magmodules** [comment]
Hi @albsa thank you for the testing! Looks like there was an update file missing, just added [UpgradeSchema.php](https://github.com/mollie/magento2/blob/1.4.0/Setup/UpgradeSchema.php), this should take care of the creation of the table on update. About the second issue, the notice during saving of the config: the module checks if all methods are also enabled in the Mollie Dashboard. This needed some change to also get back the Order API methods.

**Comment by albsa** [comment]
@Marvin-Magmodules still no success, upgrade, recompile, static redeployment, nothing helps.
The file is in the vendor folder.

Think we're still missing something!

**Comment by Marvin-Magmodules** [comment]
Hi @albsa is this the same environment you updated the last time, as it will only trigger the creation of the tables if it comes from a version below 1.4.0? Otherwise trigger the setup process by editing the setup_module table and set schema_version and data_version to 1.3.5 for Mollie_Payment and run setup:upgrade again.

**Comment by albsa** [comment]
@Marvin-Magmodules That did the trick! I am testing right now and I am encountering the following issues:

- When the Klarna payment method is cancelled (a user going back to maybe choose iDEAL for example etc.) the redirect is going to a success page.

- When a order is proceeded with a status "Authorized" or "Paid" from the mollie test environment payment page, the order stays in the "Payment Pending" status on the back-end.

This might have something to do with the 2.2.6 issue that it is stuck on pending, even if its paid. But I am not 100% on that. What another cause of this issue might be is the following:
<img width="1309" alt="schermafbeelding 2018-10-19 om 20 42 58" src="https://user-images.githubusercontent.com/8933779/47237506-9b366080-d3df-11e8-934b-dfb203924d62.png">

- The order overview is not accessable anymore after a couple Klarna orders
<img width="1548" alt="schermafbeelding 2018-10-19 om 20 40 40" src="https://user-images.githubusercontent.com/8933779/47237529-aab5a980-d3df-11e8-8189-0fa468e2b3bc.png">
Invoices is accessible.

Otherwise it might be an good idea Marvin to get in touch by phone or e-mail.
I will send an email so I can grant access to the test environment.

**Comment by Marvin-Magmodules** [comment]
If the customer redirects to Klarna (or any method using the Orders API) and then cancels the payment, the status of the payment is not changed, but still "created" instead of the expected "canceled". When using payment though the Payment API this gets changed to "canceled". Not sure why though, but it looks like a customer can not cancel an order: https://docs.mollie.com/orders/status-changes 

@Smitsel , can you shed a light on this, why are these not canceled? Do we need to change our logic for this, as this looks intended?

The other issues (orders grid) is not related to the module, but good to know these have been fixed!

**Comment by albsa** [comment]
@Smitsel @Marvin-Magmodules any updates regarding the cancel payment of Klarna? We are seeing live cases where this is happening. Now people still get redirected to a success page when the payment got denied or cancelled.
